### ISSUE TITLE
Adapter lose te conecction since update to 1.5.0

### ISSUE THREAD

**Issue by Zwer2k** [iobroker-community-adapters/ioBroker.fhem#67]
Since the update to version 1.5.0 the adapter loses the connection again and again

host.iobroker2 | 2020-05-15 22:55:37.258 | error | instance system.adapter.fhem.0 terminated with code 7 (ADAPTER_ALREADY_RUNNING)
-- | -- | -- | --
host.iobroker2 | 2020-05-15 22:55:37.257 | error | Caught by controller[0]: at process._fatalException (internal/process/execution.js:164:25)
host.iobroker2 | 2020-05-15 22:55:37.256 | error | Caught by controller[0]: at process.emit (events.js:322:22)
host.iobroker2 | 2020-05-15 22:55:37.254 | error | Caught by controller[0]: at process.<anonymous> (/opt/iobroker/node_modules/iobroker.fhem/main.js:3162:15)
host.iobroker2 | 2020-05-15 22:55:37.253 | error | Caught by controller[0]: TypeError: telnetOut.stop is not a function
host.iobroker2 | 2020-05-15 22:55:37.252 | error | Caught by controller[0]: ^
host.iobroker2 | 2020-05-15 22:55:37.250 | error | Caught by controller[0]: telnetOut.stop();
host.iobroker2 | 2020-05-15 22:55:37.248 | error | Caught by controller[0]: /opt/iobroker/node_modules/iobroker.fhem/main.js:3162

**Comment by Apollon77** [comment]
fixed in 1.5.1
